---
title: Agregar un sonido de la biblioteca
hero_image: images / banner.png
description: Cómo agregar un sonido a tu sprite de Scratch
original_url: ""
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "rasguño"
steps:
  - 
    title: Agrega un sonido a tu sprite
