---
title: Hinzufügen eines Sounds aus der Bibliothek
hero_image: images/banner.png
description: So fügen Sie Ihrem Scratch-Sprite einen Sound hinzu
original_url: ""
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "scratch"
steps:
  - 
    title: Fügen Sie Ihrem Sprite einen Sound hinzu
