---
title: Προσθήκη ήχου από τη βιβλιοθήκη
hero_image: εικόνες / banner.png
description: Πώς να προσθέσετε έναν ήχο στο Scratch sprite
original_url: ""
theme: cc-πρωτότυπο
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: "γρατσουνιά"
steps:
  - 
    title: Προσθέστε έναν ήχο στον σπρέι σας
